language: "node_js"
node_js:
  - "0.10"
  - "0.8"
  - "0.6"
  - "0.4"

before_install:
 - '[ "${TRAVIS_NODE_VERSION}" = "0.6" ] && npm conf set strict-ssl false || true'
 - "npm install istanbul -g"
 - "npm install coveralls -g"

script: "make ci-travis"

after_success:
  - "make submit-cov-to-coveralls"
